FAQs
====

:Q: Will Lantern ever cost me money?

:A: Lantern is free to view, modify, and redistribute in accordance with its `license <https://raw.github.com/getlantern/lantern/master/LICENSE>`_.


:Q: How will running Lantern affect performance on my computer?

:A: Lantern is designed to be as lightweight and unobtrusive as possible.