FAQs
====

:Q: Is there a risk in running Lantern?
:A: ...


:Q: How will running Lantern affect performance on my computer?

:A: Lantern's goal is to be as lightweight and unobtrusive as possible. In Get Mode, you shouldn't even notice it's running, other than previously-blocked sites will now be accessible. In Give Mode, a portion of your internet connection may intermittently be donated to other users, but based on the other users online at the time, you may not even notice. Limiting the resources Lantern uses while you're using your computer is currently a planned feature. (#19)


:Q: Will Lantern ever cost me money?

:A: Lantern is free as in money and as in freedom: free to use, modify, and redistribute in accordance with its `license <https://raw.github.com/getlantern/lantern/master/LICENSE>`_.


:Q: How can I contribute to the cause?

:A: run in give mode, sponsor a cloud proxy, give feedback, ask or answer questions in the forums, add or translate documentation, submit patches, bug reports, and feature requests, sponsor the development of a feature or bugfix