Manual Proxy Configuration
==========================

as of recent versions, by default Chrome, Safari, and Firefox use Mac OS X system proxy settings (XXX what happens on other platforms? other browsers?). allows you to set a system-wide http proxy once and all browsers automatically use it rather than having to configure each browser to use it.

if you would prefer not to set lantern as your system proxy (see: "under the hood" preferences), you have to explicitly configure your browser to use lantern as its http proxy rather than using the system proxy settings. when asked for the proxy's port number, use the number lantern displays next to "port" in the "under the hood" panel.

(links to per-browser instructions)

e.g. `firefox <http://support.mozilla.org/en-US/kb/Options%20window%20-%20Advanced%20panel#w_network-tab>`_

XXX combine this into [[System Proxy]] page?